### ISSUE TITLE
where clause

### ISSUE THREAD

**Issue by ErmanOzcan1** [dgadelha/FirebaseNetAdmin#1]
Hi 
can we query with where clause ? 

thanks for developing this package

**Comment by dgadelha** [comment]
Hi,

There seems to be no where in [their documentation](https://firebase.google.com/docs/database/admin/retrieve-data?hl=en#section-queries).

Although, you could try something like [equalTo](https://firebase.google.com/docs/reference/admin/node/admin.database.Query?hl=en#equalTo), which is available in this library.

Read more about [filtering data here](https://firebase.google.com/docs/database/web/lists-of-data#filtering_data).

Thanks!
