### ISSUE TITLE
Can I use FirebaseNetAdmin to secure a asp.net web api backend?

### ISSUE THREAD

**Issue by AndreasSchmid1** [dgadelha/FirebaseNetAdmin#2]
Thanks for this lib. after the app secrets are obnsolete this is exactly what i need.
btw, can FirebaseNetAdmin be used to secure Authorize a asp.net backend with it? Thank you for help in advance

**Comment by dgadelha** [comment]
By saying `secure Authorize` you mean create an authentication token? [You can do it](https://github.com/dgadelha/FirebaseNetAdmin/blob/master/FirebaseNetAdmin/Firebase/Auth/IFirebaseAdminAuth.cs#L12)

**Comment by AndreasSchmid1** [comment]
thank you! i will try this
